---
name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        type: string
jobs:
  call-maven-publish:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml
    with:
      maven_command: "clean deploy"
      java_version: '21'
      revision: ${{ inputs.revision }}
    secrets:
      maven_username: ${{ secrets.MAVEN_USER }}
      maven_password: ${{ secrets.MAVEN_PASSWORD }}
      maven_gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      maven_gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  
